spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://tripleassignment.c6wukdjxvf6m.ap-northeast-2.rds.amazonaws.com:3306/triple
    username: triple1234
    password: triple1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

#위 데이터베이스는 트리플 채용프로세스 기간동안에만 사용할 예정입니다.
#실제 테스트 필요 시 위 데이터베이스 사용이 무방합니다.